### ISSUE TITLE
setTo / setBy method  called within the "change" event have no effect

### ISSUE THREAD

**Issue by happyhj** [naver/egjs-axes#80]
## Description
The setTo / setBy method that is called synchronously within the "change" event handler caused by user interaction is not reflected in the axes coordinates. (for example, checking with axes.get ())

## Steps to check or reproduce
<img src="https://user-images.githubusercontent.com/3903575/33065088-33656e78-ceeb-11e7-94c4-d60b6c4b5f3f.gif" width="400"/>
https://codepen.io/happyhj/pen/VrQJBg

**Comment by jongmoon** [comment]
It is somewhat difficult interface to user. 

But `setTo` call in "change" handler makes recursive call because this function makes "change" event again. 

To solve this problem, axes provide function in `event` property. So if you want to change position while handling `change` event. You should use `event.set` or `event.setTo` function. Ref https://naver.github.io/egjs-axes/release/latest/doc/global.html#set

You can reference following code.

```js
const axes = new eg.Axes({
  "x": {
     range: [0, 100]
  },
  "zoom": {
     range: [50, 30]
  }
}).on("animationStart", function(event) {
  event.setTo({x: 10}, 2000);
});
```

**Comment by sculove** [comment]
How about sending message? or preventing setTo/setBy method while animation.
